[phases.setup]
nixPkgs = ['maven', 'openjdk17']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.start]
cmd = 'java -Dserver.port=$PORT -jar target/userCollection-0.0.1-SNAPSHOT.jar'
